- type: sectorService
  id: PirateBounties
  components:
  - type: SectorPirateBountyDatabase

- type: sectorService
  id: Mail
  components:
  - type: SectorLogisticStats
  - type: SectorMail # Contains sector-wide mail parameters

- type: sectorService
  id: ShuttleRecords
  components:
  - type: SectorShuttleRecords

- type: sectorService
  id: BankAccounts
  components:
  - type: SectorBank
    accounts:
      Frontier:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 18 # ~65K per hour, about enough for minimum wage for Frontier employees
      Nfsd: # Largly unused.
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 20 # 72K per hour, about enough for minimum wage for the default Militia size
      Medical:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 6 # 21.6K per hour, a bit over for the DOC MOM's wage.
      Mercenary: # Nu Sector
        !type:SectorBankAccountInfo
        balance: 0
        increasePerSecond: 2 # 7.2K per hour, most of their money is made from expeditions and contra.

 # A global source of character records (DNA, fingerprints, criminal records, etc.)
- type: sectorService
  id: SectorRecords
  components:
  - type: StationRecords

- type: sectorService
  id: Alerts
  components:
  - type: AlertLevel
    alertLevelPrototype: stationAlerts

- type: sectorService
  id: BountyContracts
  components:
  - type: BountyContractData

- type: sectorService
  id: PublicTransit
  components:
  - type: SectorPublicTransit
