- type: job
  id: NFJanitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 # mono - change to 1 hr
  startingGear: NFJanitorGear
  alwaysUseSpawner: true
  icon: "JobIconJanitor"
  supervisors: job-supervisors-sc
  weight: 100
  displayWeight: 40
  canBeAntag: false
  access:
  - Service
  - Janitor
  - Maintenance
  - External
  - Lark # Null Sector
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NFJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: NFJanitorPDA
    belt: ClothingBeltJanitorFilled
  storage:
    back:
    - EncryptionKeyService
