- type: entity
  name: splendurium coin
  parent: BaseItem
  id: SplenduriumCoin
  suffix: 20 TC
  description: A token awarded to NGC personnel for turning in contraband. It can be exchanged in an Militia uplink device for a variety of law enforcement tools.
  components:
  - type: Sprite
    sprite: _NF/Objects/Specific/Security/frontieruplinkcoin.rsi
    state: frontieruplinkcoin
  - type: Item
    sprite: _NF/Objects/Specific/Security/frontieruplinkcoin.rsi
    size: Tiny
  - type: Stack
    count: 20
    stackType: SplenduriumCoin
  - type: StaticPrice
    price: 0
  - type: StackPrice
    price: 200
  - type: Currency
    price:
      SplenduriumCoin: 1

- type: entity
  parent: SplenduriumCoin
  id: SplenduriumCoin1
  suffix: 1 TC
  components:
  - type: Stack
    count: 1

- type: entity
  parent: SplenduriumCoin
  id: SplenduriumCoin5
  suffix: 5 TC
  components:
  - type: Stack
    count: 5

- type: entity
  parent: SplenduriumCoin
  id: SplenduriumCoin10
  suffix: 10 TC
  components:
  - type: Stack
    count: 10

# Uplinks
- type: entity
  parent: [ BaseItem, StorePresetSecurityUplink ]
  id: BaseSecurityUplinkRadio
  name: militia uplink
  description: Retro looking old radio...
  suffix: Empty
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _Null/Objects/Devices/communication.rsi
    scale: 0.8, 0.8
    layers:
    - state: old-radio
  - type: Item
    sprite: _Null/Objects/Devices/communication.rsi
    heldPrefix: old-radio
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Tag
    tags:
    - SecurityUplink

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioDebug
  suffix: Security, DEBUG
  components:
  - type: Store
    balance:
      SplenduriumCoin: 99999

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioSheriff
  suffix: Colonel 20
  components:
  - type: Store
    balance:
      SplenduriumCoin: 20

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioOfficer
  suffix: Officer 15
  components:
  - type: Store
    balance:
      SplenduriumCoin: 15

#Mono

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioDeputy
  suffix: Deputy 10
  components:
  - type: Store
    balance:
      SplenduriumCoin: 10

#Mono End

- type: entity
  name: Militia deployable barrier
  id: NfsdDeployableBarrier
  description: A deployable barrier. Swipe your ID card to lock/unlock it.
  parent: DeployableBarrier
  components:
  - type: Sprite
    sprite: _NF/Objects/Specific/Security/nfsdbarrier.rsi
    layers:
    - state: idle
    - state: locked
      map: ["enum.LockVisualLayers.Lock"]
