# Lifted from Frontier
- type: job
  id: LodgeSupervisor
  name: job-name-lodge-supervisor
  description: job-description-lodge-supervisor
  playTimeTracker: JobLodgeSupervisor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hours
    - !type:RoleTimeRequirement
      role: JobMilitiaCoordinator
      time: 7200 # 2 hours
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24 hours
  whitelisted: true
  startingGear: LodgeSupervisorGear
  alwaysUseSpawner: true
  icon: JobIconSheriff
  requireAdminNotify: true
  supervisors: job-supervisors-sc
  weight: 180
  displayWeight: 70
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: LodgeSupervisorGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
    pocket2: WeaponEnergyGunMultiphase # DeltaV gun
  storage:
    back:
    - NfsdTechFabFlatpack
    - Multitool
    - HoloprojectorNfsd
    - DoorRemoteNfsd
    - BaseSecurityUplinkRadioSheriff
    - RubberStampLodgeSupervisor
