- type: job
  id: Valet
  name: job-name-valet
  description: job-description-valet
  playTimeTracker: JobValet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ValetGear
  alwaysUseSpawner: true
  icon: "JobIconValet" # Frontier: JobIconServiceWorker<JobIconValet
  supervisors: job-supervisors-sc
  weight: 60 # Frontier
  displayWeight: 10 # Frontier
  canBeAntag: false
  access:
  - Maintenance
  - External # Frontier
  - Service
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial # Frontier
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

# Frontier: valet loadout
- type: startingGear
  id: ValetGear
  equipment:
    head: ClothingHeadHatBellhop
    gloves: ClothingHandsGlovesColorWhite
    id: ValetPDA
  storage:
    back:
    - EncryptionKeyService # Frontier
# End Frontier
