- type: accessGroup
  id: CadetNfsdAccess
  tags:
  - Maintenance
  - External
  - Security
  - Brig
  
- type: accessGroup
  id: GeneralNfsdAccess
  tags:
  - Maintenance
  - External
  - Command
  - Brig
  - Security
  - Mercenary # Frontier
  - Captain # Frontier

- type: accessGroup
  id: GeneralNfsdBrigAccess
  tags:
  - Maintenance
  - External
  - Brig
  
- type: accessGroup
  id: GeneralNfsdBrigmedicAccess
  tags:
  - Maintenance
  - External
  - Command
  - Brig
  - Security
  - Mercenary # Frontier
  - Captain # Frontier
  - Chemistry
  - Medical