# PDA
- type: loadoutGroup
  id: MilitiaCoordinatorPDA
  name: loadout-group-contractor-pda    # Name is not important
  hidden: true                          # No point in showing this, it gets auto-selected.
  loadouts:
  - LodgePDAEntry
  fallbacks:
  - LodgePDAEntry
  
# Jumpsuit
- type: loadoutGroup
  id: MilitiaCoordinatorJumpsuitGroup
  name: loadout-group-mc-jumpsuit
  loadouts:
  - MCJumpsuitYellowEntry
  - HeadofSecurityJumpsuit
  - HeadofSecurityJumpskirt
  - HeadofSecurityTurtleneck
  - HeadofSecurityTurtleneckSkirt
  - HeadofSecurityFormalSuit
  - HeadofSecurityFormalSkirt