name: "Labels: Size"
on: pull_request_target
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  size-label:
    runs-on: ubuntu-latest
    env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.5"
        with:
          # Custom size configuration
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "100": "M",
              "1000": "L",
              "5000": "XL"
            }
